def failwith(message: str):
    raise Exception(message)

